services:
  certificatemanager:
    image: php:8.4-apache-trixie
    container_name: certificatemanager
    ports:
      - "8100:80"
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped